### ISSUE TITLE
Raw cell positions

### ISSUE THREAD

**Issue by PolarBean** [delkind/mouse-brain-cell-counting#1]
Seriously fantastic project! I noticed that the cells were viewable in the allen STPt images but its amazing to see the project you have put together. I'm wondering if there is somewhere I could obtain the XYZ cell coordinates for each animal as I would like to view them in meshview (https://meshview.apps.hbp.eu/?atlas=ABA_Mouse_CCFv3_2015_25um), a point cloud viewer. If you could provide me with the positions I would be very grateful. 
all the best, 

Harry

**Comment by delkind** [comment]
Thank you, @PolarBean ! Replied by email.
